export const GET_QUESTIONS_REQUEST = "GET_QUESTIONS_REQUEST";
export const GET_QUESTIONS_SUCCESS = "GET_QUESTIONS_SUCCESS";
export const GET_QUESTIONS_FAILURE = "GET_QUESTIONS_FAILURE";

export const ADD_QUESTION_REQUEST = "ADD_QUESTION_REQUEST";
export const ADD_QUESTION_SUCCESS = "ADD_QUESTION_SUCCESS";
export const ADD_QUESTION_FAILURE = "ADD_QUESTION_FAILURE";

export const UPDATE_QUESTION_REQUEST = "UPDATE_QUESTION_REQUEST";
export const UPDATE_QUESTION_SUCCESS = "UPDATE_QUESTION_SUCCESS";
export const UPDATE_QUESTION_FAILURE = "UPDATE_QUESTION_FAILURE";

export const DELETE_QUESTION_BY_QUESTION_iD_REQUEST = "DELETE_QUESTION_BY_QUESTION_iD_REQUEST";
export const DELETE_QUESTION_BY_QUESTION_ID_SUCCESS = "DELETE_QUESTION_BY_QUESTION_ID_SUCCESS";
export const DELETE_QUESTION_BY_QUESTION_ID_FAILURE = "DELETE_QUESTION_BY_QUESTION_ID_FAILURE";

export const GET_CATEGORY_REQUEST = "GET_CATEGORY_REQUEST";
export const GET_CATEGORY_SUCCESS = "GET_CATEGORY_SUCCESS";
export const GET_CATEGORY_FAILURE = "GET_CATEGORY_FAILURE";

export const ADD_CATEGORY_REQUEST = "ADD_CATEGORY_REQUEST";
export const ADD_CATEGORY_SUCCESS = "ADD_CATEGORY_SUCCESS";
export const ADD_CATEGORY_FAILURE = "ADD_CATEGORY_FAILURE";
//QUIZ NAME
export const GET_QUIZ_NAME_REQUEST = "GET_QUIZ_NAME_REQUEST";
export const GET_QUIZ_NAME_SUCCESS = "GET_QUIZ_NAME_SUCCESS";
//export const ADD_CATEGORY_FAILURE = "ADD_CATEGORY_FAILURE";

//ADD QUIZ NAME
export const ADD_QUIZ_NAME_REQUEST = "ADD_QUIZ_NAME_REQUEST";
export const ADD_QUIZ_NAME_SUCCESS = "ADD_QUIZ_NAME_SUCCESS";
export const ADD_QUIZ_NAME_FAILURE = "ADD_QUIZ_NAME_FAILURE";

//GET FINALIZED QUIZ 
export const GET_FINALIZE_QUIZ_REQUEST = "GET_FINALIZE_QUIZ_REQUEST";
export const GET_FINALIZE_QUIZ_SUCCESS = "GET_FINALIZE_QUIZ_SUCCESS";
export const GET_FINALIZE_QUIZ_FAILURE = "GET_FINALIZE_QUIZ_FAILURE";

//GET FINALIZED QUIZ 
export const GET_FINALIZE_QUIZ_URL_REQUEST = "GET_FINALIZE_QUIZ_URL_REQUEST";
export const GET_FINALIZE_QUIZ_URL_SUCCESS = "GET_FINALIZE_QUIZ_URL_SUCCESS";
export const GET_FINALIZE_QUIZ_URL_FAILURE = "GET_FINALIZE_QUIZ_URL_FAILURE";

//DELETE HOST QUIZ
export const DELETE_QUIZ_FROM_HOST_REQUEST = "DELETE_QUIZ_FROM_HOST_REQUEST";
export const DELETE_QUIZ_FROM_HOST_SUCCESS = "DELETE_QUIZ_FROM_HOST_SUCCESS";
export const DELETE_QUIZ_FROM_HOST_FAILURE = "DELETE_QUIZ_FROM_HOST_FAILURE";

//HOST QUIZ
export const HOST_QUIZ_REQUEST = "HOST_QUIZ_REQUEST";
export const HOST_QUIZ_SUCCESS = "HOST_QUIZ_SUCCESS";
export const HOST_QUIZ_FAILURE = "HOST_QUIZ_FAILURE";

// Players in quiz

export const GET_PLAYERS_DETAILS_GAME_REQUEST = "GET_PLAYERS_DETAILS_GAME_REQUEST";
export const GET_PLAYERS_DETAILS_GAME_SUCCESS = "GET_PLAYERS_DETAILS_GAME_SUCCESS";
export const GET_PLAYERS_DETAILS_GAME_FAILURE = "GET_PLAYERS_DETAILS_GAME_FAILURE";