
export const VALIDATE_OTP_BY_EMAIL_REQUEST = "VALIDATE_OTP_BY_EMAIL_REQUEST";
export const VALIDATE_OTP_BY_EMAIL_SUCCESS = "VALIDATE_OTP_BY_EMAIL_SUCCESS";
export const VALIDATE_OTP_BY_EMAIL_FAILURE = "VALIDATE_OTP_BY_EMAIL_FAILURE";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const GENERATE_OTP_BY_EMAIL_REQUEST = "GENERATE_OTP_BY_EMAIL_REQUEST";
export const GENERATE_OTP_BY_EMAIL_SUCCESS = "GENERATE_OTP_BY_EMAIL_SUCCESS";
export const GENERATE_OTP_BY_EMAIL_FAILURE = "GENERATE_OTP_BY_EMAIL_FAILURE";

export const GET_USER_DETAILS_REQUEST = "GET_USER_DETAILS_REQUEST";
export const GET_USER_DETAILS_SUCCESS = "GET_USER_DETAILS_SUCCESS";
export const GET_USER_DETAILS_FAILURE = "GET_USER_DETAILS_FAILURE";





export const GET_HOUR_LIST_BY_USER_ID_REQUEST =
  "GET_HOUR_LIST_BY_USER_ID_REQUEST";
export const GET_HOUR_LIST_BY_USER_ID_SUCCESS =
  "GET_HOUR_LIST_BY_USER_ID_SUCCESS";
export const GET_HOUR_LIST_BY_USER_ID_FAILURE =
  "GET_HOUR_LIST_BY_USER_ID_FAILURE";