import React from 'react'

const Privacy = () => {

    return (
<>

    <div className="max-w-4xl mx-auto p-6">
      {/* Title */}
      <h1 className="text-4xl font-bold text-center underline mb-8">Privacy Policy</h1>
      <p>Last updated: March 07, 2025</p>
      <section className="mb-8">
        <p className="text-lg">
          This Privacy Policy describes Our policies and procedures on the collection, use, and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
        </p>
        <p className="mt-2 text-lg">
          We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
        </p>
      </section>

      {/* Interpretation and Definitions */}
      <section className="mb-8">
        <h2 className="text-2xl font-semibold underline">Interpretation and Definitions</h2>
        <h3 className="text-xl font-semibold mt-4">Interpretation</h3>
        <p className="mt-2">
          The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or plural.
        </p>
        
        <h3 className="text-xl font-semibold mt-4">Definitions</h3>
        <p className="mt-2">For the purposes of this Privacy Policy:</p>
        <ul className="list-disc pl-6 mt-2">
          <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
          <li><strong>Affiliate</strong> means an entity that controls, is controlled by, or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
          <li><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to NORDIND DEVELOPMENT AS, Louises gate 18B, 0169, Oslo. For the purpose of the GDPR, the Company is the Data Controller.</li>
          <li><strong>Cookies</strong> are small files placed on Your computer, mobile device, or other device by a website containing details of Your browsing history on that website among other uses.</li>
          <li><strong>Country</strong> refers to: Norway.</li>
          <li><strong>Data Controller</strong> for the purposes of the GDPR (General Data Protection Regulation),refers to the Company as the legal person which alone or jointly with others determines the purposes and means of the processing of Personal Data.</li>
          <li><strong>Device</strong> means any device that can access the Service such as a computer, cellphone, or tablet.</li>
          <li><strong>GDPR</strong> refers to EU General Data Protection Regulation.</li>
          <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual. This includes names, identification numbers, online identifiers, etc.</li>
          <li><strong>Service</strong> refers to the Website.</li>
          <li><strong>Service Provider</strong> refers to any third party who processes the data on behalf of the Company.</li>
          <li><strong>Third-party Social Media Service</strong> refers to any website or social network site through which a User can log in or create an account to use the Service.</li>
          <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (e.g., the duration of a page visit).</li>
          <li><strong>Website</strong> refers to Quizprompter, accessible from <a href="https://host.quizprompter.com" className="text-blue-500 underline">quizprompter.com</a>.</li>
          <li><strong>You</strong> refers to the individual accessing or using the Service, or the company or other legal entity on behalf of which such individual is accessing or using the Service.</li>
          <li><strong> Under GDPR,</strong> You can be referred to as the Data Subject or as the User as you are the individual using the Service.</li>
        </ul>
      </section>
      {/* Part 1: Collecting and Using Your Personal Data */}
      <section className="mb-8">
        <h2 className="text-2xl font-semibold underline">Collecting and Using Your Personal Data</h2>
        <h3 className="text-xl font-semibold underline mt-4">Types of Data Collected </h3>
        <h3 className="text-xl font-semibold underline mt-4">Personal Data </h3>
        <p className="mt-4">
          While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
        </p>
        <ul className="list-disc pl-6 mt-2">
          <li>Email address</li>
          <li>First name and last name</li>
          <li>Usage Data</li>
        </ul>
        <h3 className="text-xl font-semibold underline mt-4">Usage Data</h3>
        <p className="mt-2">
        Usage Data may include information such as Your Device's Internet Protocol
address (e.g. IP address), browser type, browser version, the pages of our
Service that You visit, the time and date of Your visit, the time spent on
those pages, unique device identifiers and other diagnostic data.
        </p>
        <p className="mt-2">
        When You access the Service by or through a mobile device, We may collect
certain information automatically, including, but not limited to, the type of
mobile device You use, Your mobile device unique ID, the IP address of Your
mobile device, Your mobile operating system, the type of mobile Internet
browser You use, unique device identifiers and other diagnostic data.
        </p>
        <p className="mt-2">
          We may collect Personal data that is already associated with Your Third-Party Social Media Service's account, such as Your name, email, activities, or contact list.
        </p>
      </section>

      <section className="mb-8">
      <h2 className="text-2xl font-semibold underline">Information from Third-Party Social Media Services</h2>
      <p className="mt-2">
      The Company allows You to create an account and log in to use the Service
      through the following Third-party Social Media Services:
        </p>

        <ul className="list-disc pl-6 mt-2">
          <li>Google</li>
          <li>Facebook</li>
          <li>Instagram</li>
          <li>Twitter</li>
          <li>LinkedIn</li>
        </ul>

        <p className="mt-2">
        If You decide to register through or otherwise grant us access to a Third-
Party Social Media Service, We may collect Personal data that is already
associated with Your Third-Party Social Media Service's account, such as Your
name, Your email address, Your activities or Your contact list associated with
that account.
        </p>
        <p className="mt-2">
        You may also have the option of sharing additional information with the
Company through Your Third-Party Social Media Service's account. If You choose
to provide such information and Personal Data, during registration or
otherwise, You are giving the Company permission to use, share, and store it
in a manner consistent with this Privacy Policy.
        </p>
        </section>
      {/* Part 2: Tracking Technologies and Cookies */}
      <section className="mb-8">
        <h2 className="text-2xl font-semibold underline">Tracking Technologies and Cookies</h2>
        <p className="mt-4">
          We use Cookies and similar tracking technologies to monitor and improve our Service. These include:
        </p>
        <ul className="list-disc pl-6 mt-2">
        <li><strong>Cookies</strong>  A cookie is a small file placed on Your
    Device. You can instruct Your browser to refuse all Cookies or to indicate
    when a Cookie is being sent. However, if You do not accept Cookies, You
    may not be able to use some parts of our Service. Unless you have adjusted
    Your browser setting so that it will refuse Cookies, our Service may use
    Cookies.</li>
        <li><strong>Web Beacons</strong> Certain sections of our Service and our emails may contain
    small electronic files known as web beacons (also referred to as clear
    gifs, pixel tags, and single-pixel gifs) that permit the Company, for
    example, to count users who have visited those pages or opened an email
    and for other related website statistics (for example, recording the
    popularity of a certain section and verifying system and server
    integrity).</li>
        </ul>
        <p className="mt-2">
        Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies remain on
Your personal computer or mobile device when You go offline, while Session
Cookies are deleted as soon as You close Your web browser. You can learn more
about cookies on [TermsFeed
website](https://www.termsfeed.com/blog/cookies/#What_Are_Cookies) article.
        </p>
        <p className="mt-2">
          We use both Session and Persistent Cookies for different purposes:
        </p>
        <ul className="list-disc pl-6 mt-2">
        <li><strong>Necessary / Essential Cookies</strong> </li>
        <li><strong>Type: </strong> Session Cookies</li>
        <li><strong>Administered by: </strong> Us </li>
        </ul>
        <p className="mt-2">
        <strong>Purpose:</strong>These Cookies are essential to provide You with services
    available through the Website and to enable You to use some of its
    features. They help to authenticate users and prevent fraudulent use of
    user accounts. Without these Cookies, the services that You have asked for
    cannot be provided, and We only use these Cookies to provide You with
    those services.
        </p>
        <ul className="list-disc pl-6 mt-2">
        <li><strong>Cookies Policy / Notice Acceptance Cookies</strong> </li>
        <li><strong>Type: </strong> Persistent Cookies </li>
        <li><strong>Administered by: </strong> Us </li>
        </ul>
        <p className="mt-2">
        <strong>Purpose:</strong>These Cookies identify if users have accepted the use of cookies
        on the Website.
        </p>
        <ul className="list-disc pl-6 mt-2">
        <li><strong>Functionality Cookies</strong> </li>
        <li><strong>Type: </strong> Persistent Cookies </li>
        <li><strong>Administered by: </strong> Us </li>
        </ul>
        <p className="mt-2">
        <strong>Purpose:</strong>These Cookies allow us to remember choices You make when You use
    the Website, such as remembering your login details or language
    preference. The purpose of these Cookies is to provide You with a more
    personal experience and to avoid You having to re-enter your preferences
    every time You use the Website.
        </p>
        <ul className="list-disc pl-6 mt-2">
        <li><strong>Targeting and Advertising Cookies</strong> </li>
        <li><strong>Type: </strong> Persistent Cookies </li>
        <li><strong>Administered by: </strong> Third-Parties </li>
        </ul>
        <p className="mt-2">
        <strong>Purpose:</strong>These Cookies track your browsing habits to enable Us to show
    advertising which is more likely to be of interest to You. These Cookies
    use information about your browsing history to group You with other users
    who have similar interests. Based on that information, and with Our
    permission, third party advertisers can place Cookies to enable them to
    show adverts which We think will be relevant to your interests while You
    are on third party websites.
        </p>
        <p className="mt-2">
        For more information about the cookies we use and your choices regarding
cookies, please visit our Cookies Policy or the Cookies section of our Privacy
Policy.
        </p>
      </section>

      {/* Part 3: Use of Your Personal Data */}
      <section className="mb-8">
        <h2 className="text-2xl font-semibold underline">Use of Your Personal Data</h2>
        <p className="mt-4">
          The Company may use Your Personal Data for the following purposes:
        </p>
        <ul className="list-disc pl-6 mt-2">
          <li>To provide and maintain our Service , including to monitor the usage of
          our Service.</li>
          <li>To manage Your Account: to manage Your registration as a user of the
    Service. The Personal Data You provide can give You access to different
    functionalities of the Service that are available to You as a registered
    user.</li>
          <li>For the performance of a contract: the development, compliance and
    undertaking of the purchase contract for the products, items or services
    You have purchased or of any other contract with Us through the Service</li>
          <li>To contact You: To contact You by email, telephone calls, SMS, or other
    equivalent forms of electronic communication, such as a mobile
    application's push notifications regarding updates or informative
    communications related to the functionalities, products or contracted
    services, including the security updates, when necessary or reasonable for
    their implementation.</li>
          <li>To provide You with news, special offers and general information about
    other goods, services and events which we offer that are similar to those
    that you have already purchased or enquired about unless You have opted
    not to receive such information.</li>
          <li>To manage Your requests: To attend and manage Your requests to Us.</li>
          <li>For business transfers: We may use Your information to evaluate or conduct
    a merger, divestiture, restructuring, reorganization, dissolution, or
    other sale or transfer of some or all of Our assets, whether as a going
    concern or as part of bankruptcy, liquidation, or similar proceeding, in
    which Personal Data held by Us about our Service users is among the assets
    transferred.</li>
          <li>For other purposes : We may use Your information for other purposes, such
    as data analysis, identifying usage trends, determining the effectiveness
    of our promotional campaigns and to evaluate and improve our Service,
    products, services, marketing and your experience.</li>
        </ul>
        <p className="mt-2">
        We may share Your personal information may be shared in the following situations:
        </p>
        <ul className="list-disc pl-6 mt-2">
          <li>With Service Providers: We may share Your personal information with
    Service Providers to monitor and analyze the use of our Service, to show
    advertisements to You to help support and maintain Our Service, for
    payment processing, to contact You.</li>
          <li>For business transfers: We may share or transfer Your personal information
    in connection with, or during negotiations of, any merger, sale of Company
    assets, financing, or acquisition of all or a portion of Our business to
    another company.</li>
          <li>With Affiliates: We may share Your information with Our affiliates, in
    which case we will require those affiliates to honor this Privacy Policy.
    Affiliates include Our parent company and any other subsidiaries, joint
    venture partners or other companies that We control or that are under
    common control with Us.</li>
          <li>With business partners: We may share Your information with Our business
          partners to offer You certain products, services or promotions.</li>
          <li>With other users: when You share personal information or otherwise
    interact in the public areas with other users, such information may be
    viewed by all users and may be publicly distributed outside. If You
    interact with other users or register through a Third-Party Social Media
    Service, Your contacts on the Third-Party Social Media Service may see
    Your name, profile, pictures and description of Your activity. Similarly,
    other users will be able to view descriptions of Your activity,
    communicate with You and view Your profile.</li>
          <li>With Your consent : We may disclose Your personal information for any
          other purpose with Your consent.</li>
        </ul>
      </section>

      {/* Part 4: Retention and Security of Your Personal Data */}
      <section className="mb-8">
        <h2 className="text-2xl font-semibold underline">Retention of Your Personal Data</h2>
        <p className="mt-2">   
The Company will retain Your Personal Data only for as long as is necessary
for the purposes set out in this Privacy Policy. We will retain and use Your
Personal Data to the extent necessary to comply with our legal obligations
(for example, if we are required to retain your data to comply with applicable
laws), resolve disputes, and enforce our legal agreements and policies.
        </p>
        <p className="mt-2">   
        The Company will also retain Usage Data for internal analysis purposes. Usage
Data is generally retained for a shorter period of time, except when this data
is used to strengthen the security or to improve the functionality of Our
Service, or We are legally obligated to retain this data for longer time
periods.
        </p>
        <h3 className="text-xl font-semibold underline mt-4">Transfer of Your Personal Data</h3>
        <p className="mt-2">
        Your information, including Personal Data, is processed at the Company's
operating offices and in any other places where the parties involved in the
processing are located. It means that this information may be transferred to —
and maintained on — computers located outside of Your state, province, country
or other governmental jurisdiction where the data protection laws may differ
than those from Your jurisdiction.
        </p>
        <p className="mt-2">
        Your consent to this Privacy Policy followed by Your submission of such
        information represents Your agreement to that transfer.
        </p>
        <p className="mt-2">
        The Company will take all steps reasonably necessary to ensure that Your data
is treated securely and in accordance with this Privacy Policy and no transfer
of Your Personal Data will take place to an organization or a country unless
there are adequate controls in place including the security of Your data and
other personal information.
        </p>
        <h3 className="text-xl font-semibold underline mt-4">
        Delete Your Personal Data </h3>
        <p className="mt-2">
        You have the right to delete or request that We assist in deleting the
        Personal Data that We have collected about You.
        </p>
        <p className="mt-2">
        Our Service may give You the ability to delete certain information about You
from within the Service.
        </p>
        <p className="mt-2">
        You may update, amend, or delete Your information at any time by signing in to
Your Account, if you have one, and visiting the account settings section that
allows you to manage Your personal information. You may also contact Us to
request access to, correct, or delete any personal information that You have
provided to Us.
        </p>
        <p className="mt-2">
        Please note, however, that We may need to retain certain information when we
        have a legal obligation or lawful basis to do so.
        </p>
        <h3 className="text-2xl font-semibold underline">Disclosure of Your Personal Data  </h3>
      </section>
      <section className="mb-8">
        <h2 className="text-2xl font-semibold underline">Business Transactions  </h2>
        <p className="mt-2">
        If the Company is involved in a merger, acquisition or asset sale, Your
Personal Data may be transferred. We will provide notice before Your Personal
Data is transferred and becomes subject to a different Privacy Policy.
        </p>
        <h2 className="text-2xl font-semibold underline">Law enforcement </h2>
        <p className="mt-2">
        Under certain circumstances, the Company may be required to disclose Your
Personal Data if required to do so by law or in response to valid requests by
public authorities (e.g. a court or a government agency).
        </p>
        <h2 className="text-2xl font-semibold underline">Other legal requirements  </h2>
        <p className="mt-2">
        The Company may disclose Your Personal Data in the good faith belief that such
        action is necessary to:
        <ul className="list-disc pl-6 mt-2">
          <li>Comply with a legal obligation</li>
          <li>Protect and defend the rights or property of the Company</li>
          <li>Prevent or investigate possible wrongdoing in connection with the Service</li>
          <li>Protect the personal safety of Users of the Service or the public</li>
          <li>Protect against legal liability</li>
        </ul>
        </p>
        <h2 className="text-2xl font-semibold underline">Security of Your Personal Data  </h2>
        <p className="mt-2">
        The security of Your Personal Data is important to Us, but remember that no
method of transmission over the Internet, or method of electronic storage is
100% secure. While We strive to use commercially acceptable means to protect
Your Personal Data, We cannot guarantee its absolute security.
        </p>
        <h2 className="text-2xl font-semibold underline">Detailed Information on the Processing of Your Personal Data </h2>
        <p className="mt-2">
        The Service Providers We use may have access to Your Personal Data. These
third-party vendors collect, store, use, process and transfer information
about Your activity on Our Service in accordance with their Privacy Policies.
        </p>
        <h2 className="text-2xl font-semibold underline">Advertising </h2>
        <p className="mt-2">
        We may use Service Providers to show advertisements to You to help support and
        maintain Our Service.
        <ul className="list-disc pl-6 mt-2">
          <li>Google AdSense & DoubleClick Cookie</li>
          <li> Google, as a third party vendor, uses cookies to serve ads on our Service.
    Google's use of the DoubleClick cookie enables it and its partners to
    serve ads to our users based on their visit to our Service or other
    websites on the Internet.</li>
          <li>You may opt out of the use of the DoubleClick Cookie for interest-based
    advertising by visiting the Google Ads Settings web page:
    <a href="http://www.google.com/ads/preferences/"></a> </li>
        </ul>
        </p>
        <h2 className="text-2xl font-semibold underline">Payments</h2>
        <p className="mt-2">
        We may provide paid products and/or services within the Service. In that case,
we may use third-party services for payment processing (e.g. payment
processors).</p>
<p className="mt-2">
We will not store or collect Your payment card details. That information is
provided directly to Our third-party payment processors whose use of Your
personal information is governed by their Privacy Policy. These payment
processors adhere to the standards set by PCI-DSS as managed by the PCI
Security Standards Council, which is a joint effort of brands like Visa,
Mastercard, American Express and Discover. PCI-DSS requirements help ensure
the secure handling of payment information.
        <ul className="list-disc pl-6 mt-2">
          <li>Stripe</li>
          <li>Their Privacy Policy can be viewed at <a href="https://stripe.com/us/privacy"/></li>
          <li>Prevent or investigate possible wrongdoing in connection with the Service</li>
        </ul>
        </p>
        <h3 className="text-2xl font-semibold underline">GDPR Privacy  </h3>
        </section>
        <section className="mb-8">
        <h2 className="text-2xl font-semibold underline">Legal Basis for Processing Personal Data under GDPR </h2>
        <p className="mt-4">
        We may process Personal Data under the following conditions:
        </p>
        <ul className="list-disc pl-6 mt-2">
          <li>Consent: You have given Your consent for processing Personal Data for one
          or more specific purposes.</li>
          <li>Performance of a contract: Provision of Personal Data is necessary for the
    performance of an agreement with You and/or for any pre-contractual
    obligations thereof.</li>
          <li>Legal obligations: Processing Personal Data is necessary for compliance
          with a legal obligation to which the Company is subject.</li>
          <li>Vital interests: Processing Personal Data is necessary in order to protect
          Your vital interests or of another natural person.</li>
          <li> Public interests: Processing Personal Data is related to a task that is
    carried out in the public interest or in the exercise of official
    authority vested in the Company.</li>
          <li>Legitimate interests: Processing Personal Data is necessary for the
          purposes of the legitimate interests pursued by the Company.</li>
          <p className="mt-2">In any case, the Company will gladly help to clarify the specific legal basis
that applies to the processing, and in particular whether the provision of
Personal Data is a statutory or contractual requirement, or a requirement
necessary to enter into a contract.</p>
        </ul>
        </section>
      {/* Part 5: Your Rights and Legal Requirements */}
      <section className="mb-8">
        <h2 className="text-2xl font-semibold underline">Your Rights under the GDPR  </h2>
        <p className="mt-4">
        The Company undertakes to respect the confidentiality of Your Personal Data
and to guarantee You can exercise Your rights.
        </p>
        <p className="mt-2">
        You have the right under this Privacy Policy, and by law if You are within the
        EU, to:
        </p>
        <ul className="list-disc pl-6 mt-2">
          <li>Request access to Your Personal Data. The right to access, update or
    delete the information We have on You. Whenever made possible, you can
    access, update or request deletion of Your Personal Data directly within
    Your account settings section. If you are unable to perform these actions
    yourself, please contact Us to assist You. This also enables You to
    receive a copy of the Personal Data We hold about You.</li>
          <li> Request correction of the Personal Data that We hold about You. You have
    the right to have any incomplete or inaccurate information We hold about
    You corrected.</li>
          <li>Object to processing of Your Personal Data. This right exists where We are
    relying on a legitimate interest as the legal basis for Our processing and
    there is something about Your particular situation, which makes You want
    to object to our processing of Your Personal Data on this ground. You also
    have the right to object where We are processing Your Personal Data for
    direct marketing purposes.</li>
          <li>Request erasure of Your Personal Data. You have the right to ask Us to
    delete or remove Personal Data when there is no good reason for Us to
    continue processing it.</li>
          <li>Request the transfer of Your Personal Data. We will provide to You, or to
    a third-party You have chosen, Your Personal Data in a structured,
    commonly used, machine-readable format. Please note that this right only
    applies to automated information which You initially provided consent for
    Us to use or where We used the information to perform a contract with You.</li>
          <li>Withdraw Your consent. You have the right to withdraw Your consent on
    using your Personal Data. If You withdraw Your consent, We may not be able
    to provide You with access to certain specific functionalities of the
    Service.</li>
        </ul>
        <h3 className="text-xl font-semibold underline mt-4">Exercising of Your GDPR Data Protection Rights  </h3>
        <p className="mt-2">
        You may exercise Your rights of access, rectification, cancellation and
opposition by contacting Us. Please note that we may ask You to verify Your
identity before responding to such requests. If You make a request, We will
try our best to respond to You as soon as possible.
        </p>
        <p className="mt-2">
        You have the right to complain to a Data Protection Authority about Our
collection and use of Your Personal Data. For more information, if You are in
the European Economic Area (EEA), please contact Your local data protection
authority in the EEA.
        </p>
        <h3 className="text-xl font-semibold underline mt-4">Children's Privacy</h3>
        <p className="mt-2">
        The Service may contain content appropriate for children under the age of 13.
As a parent, you should know that through the Service children under the age
of 13 may participate in activities that involve the collection or use of
personal information. We use reasonable efforts to ensure that before we
collect any personal information from a child, the child's parent receives
notice of and consents to our personal information practices.
        </p>
        <p className="mt-2">
        We also may limit how We collect, use, and store some of the information of
Users between 13 and 18 years old. In some cases, this means We will be unable
to provide certain functionality of the Service to these Users. If We need to
rely on consent as a legal basis for processing Your information and Your
country requires consent from a parent, We may require Your parent's consent
before We collect and use that information.
        </p>
        <p className="mt-2">
        We may ask a User to verify its date of birth before collecting any personal
information from them. If the User is under the age of 13, the Service will be
either blocked or redirected to a parental consent process.
        </p>
      </section>
      <section className="mb-8">
        <h2 className="text-2xl font-semibold underline">Information Collected from Children Under the Age of 13</h2>
        <p className="mt-2">
The Company may collect and store persistent identifiers such as cookies or IP
addresses from Children without parental consent for the purpose of supporting
the internal operation of the Service.
          </p>
          <p className="mt-2">
          We may collect and store other personal information about children if this
information is submitted by a child with prior parent consent or by the parent
or guardian of the child.
          </p>
          <p className="mt-2">
          The Company may collect and store the following types of personal information
about a child when submitted by a child with prior parental consent or by the
parent or guardian of the child:
          </p>
          <ul className="list-disc pl-6 mt-2">  
          <li>First and/or last name</li>
          <li>Date of birth</li>
          <li>Gender</li>
          <li>Grade level</li>
          <li>Email address</li>
          <li>Telephone number</li>
          <li>Parent's or guardian's name</li>
          <li>Parent's or guardian's email address</li>
          </ul>
          <p className="mt-2">
          For further details on the information We might collect, You can refer to the
"Types of Data Collected" section of this Privacy Policy. We follow our
standard Privacy Policy for the disclosure of personal information collected
from and about children.
          </p>
          </section>
      {/* Parental Access */}
      <section className="mb-8">
        <h2 className="text-2xl font-semibold underline">Parental Access</h2>
        <p className="mt-4">
        A parent who has already given the Company permission to collect and use his
        child personal information can, at any time:
        </p>
        <ul className="list-disc pl-6 mt-2">
          <li>Review, correct or delete the child's personal information</li>
          <li>Discontinue further collection or use of the child's personal information</li>
          </ul>
          <p className="mt-2">
          To make such a request, You can write to Us using the contact information
          provided in this Privacy Policy.
        </p>
      </section>

      {/* Links to Other Websites */}
      <section className="mb-8">
        <h2 className="text-2xl font-semibold underline">Links to Other Websites</h2>
        <p className="mt-4">
          Our Service may contain links to other websites not operated by us. We recommend reviewing the Privacy Policies of those websites.
        </p>
        <p className="mt-2">
        We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.
        </p>
      </section>

      {/* Changes to Privacy Policy */}
      <section className="mb-8">
        <h2 className="text-2xl font-semibold underline">Changes to this Privacy Policy</h2>
        <p className="mt-4">
          We may update this Privacy Policy from time to time. We will notify you about any changes by posting the updated policy on this page.
        </p>
        <p className="mt-4">
        We will let You know via email and/or a prominent notice on Our Service, prior
to the change becoming effective and update the "Last updated" date at the top
of this Privacy Policy.
        </p>
        <p className="mt-4">
        You are advised to review this Privacy Policy periodically for any changes.
Changes to this Privacy Policy are effective when they are posted on this
page.
        </p>
      </section>

      {/* Contact Us */}
      <section className="mb-8">
        <h2 className="text-2xl font-semibold underline">Contact Us</h2>
        <p className="mt-4">
          If you have any questions or concerns about this Privacy Policy, you can contact us at: <a href="https://host.quizprompter.com" target="" className="text-blue-500 underline">quizprompter.com</a>
        </p>
      </section>
    </div>
    
      </>
    );
  };
  

export default Privacy